### ISSUE TITLE
New tag for warning fixes

### ISSUE THREAD

**Issue by rcorre** [SiegeLord/DAllegro5#23]
It would be nice to have a new tag (or tags, for 5.0/5.1) for the fix introduced by https://github.com/SiegeLord/DAllegro5/commit/aebafd30593c98148b3c1480ffba2d1cd023371b.

Tagged versions are a bit nicer to use with dub (dub complains about branch version specifications).

**Comment by SiegeLord** [comment]
Done. Thanks for bringing it up.

**Comment by rcorre** [comment]
Awesome, thanks!
