### ISSUE TITLE
update to allegro 5.2?

### ISSUE THREAD

**Issue by GassaFM** [SiegeLord/DAllegro5#32]
What does it take to update the bindings to 5.2?

For the record, I've just tried taking 5.1 branch and changing the version number.
Then, the little functionality I use worked as before against 5.2.0 binaries.

**Comment by rcorre** [comment]
Yep, usually the version number is the minimum required. If 5.2 is officially out, I could probably update the bindings pretty quickly. Normally I just diff the Allegro headers between versions and apply the same changes to the d bindings.

**Comment by rcorre** [comment]
This can be closed, I think. `master` is working with 5.2.

**Comment by SiegeLord** [comment]
Yep, thanks.
