### ISSUE TITLE
Using dub to compile programs - macOS

### ISSUE THREAD

**Issue by joelcnz** [SiegeLord/DAllegro5#38]
The example program works, but how do I use dub for my programs?

**Comment by SiegeLord** [comment]
There's some documentation here: https://code.dlang.org/getting_started, but I've never tried it.

**Comment by rcorre** [comment]
I wrote a few games using DAllegro and dub a while back, you can take a look at [damage control](https://github.com/rcorre/damage_control) or [terra arcana](https://github.com/rcorre/terra-arcana) as an example. They contain configurations for linking allegro statically and dynamically. They work on linux and possibly Windows, I never tested on mac.

**Comment by joelcnz** [comment]
I didn't find the dub getting started much help.

Thanks rcorre for your game links.
